/**
 * ════════════════════════════════════════════════════════════════════════════
 *  GERÇEK ARAÇ AĞACI — TÜR / MARKA / MODEL
 * ════════════════════════════════════════════════════════════════════════════
 *
 *  KAYNAK: Kullanıcının sağladığı katalog ekran görüntüleri (2026-08).
 *  Ürün adetleri kasıtlı olarak alınmamıştır; yalnızca listelerin SIRASI
 *  popülerlik göstergesi olarak `sortOrder` alanına yansıtılmıştır.
 *
 *  ⚠ ÖNEMLİ — BU DOSYADA MOTOR VERİSİ YOKTUR.
 *  Kaynak ekranlarda tür → marka → model bilgisi vardır; motor adı ve motor
 *  kodu yoktur. Uyumluluk eşleştirmesi motor seviyesinde çalıştığı için
 *  motor katmanı ayrıca (ARAC_AGACI içe aktarımıyla) doldurulmalıdır.
 *  Bu dosya yalnızca ağacın üst üç katmanını kurar.
 *
 *  Kalan markaların modelleri geldikçe `MODELS` haritasına eklenir; marka
 *  listesi değişmez. Model listesi boş olan markalar veritabanına marka
 *  olarak yazılır, model yazılmaz.
 */

export type RealBrand = {
  /** Ekranda görünen ad — sadeleştirilmiş yazım (ör. 'MERCEDES BENZ' → 'Mercedes-Benz') */
  name: string
  /** Kaynaktaki ham yazım — izlenebilirlik için saklanır */
  sourceName: string
  /** Slug (URL). Boş bırakılırsa `slugify(name)` kullanılır. */
  slug?: string
  /** Bağlı olduğu araç türü slug'ları — bir marka birden çok türde olabilir */
  types: string[]
  /** Bu markanın slug'ı daha önce başka yazılmışsa eski slug (taşıma için) */
  aliasSlugs?: string[]
  country?: string
}

export const REAL_VEHICLE_TYPES = [
  { name: 'Otomobil & Hafif Ticari', slug: 'otomobil', icon: 'car', sortOrder: 10 },
  { name: 'Ağır Vasıta', slug: 'agir-vasita', icon: 'truck', sortOrder: 20 },
] as const

/**
 * Otomobil & Hafif Ticari markaları — kaynaktaki sırayla.
 * Ağır vasıta listesinde de geçen markalar (Mercedes, Iveco, Renault, Volvo,
 * Ford) TEK marka kaydıdır; `types` alanında iki tür birden bulunur.
 */
export const REAL_BRANDS: RealBrand[] = [
  // ── Otomobil & Hafif Ticari ────────────────────────────────────────────────
  { name: 'Volkswagen', sourceName: 'VOLKSWAGEN', types: ['otomobil'], country: 'Almanya' },
  { name: 'Mercedes-Benz', sourceName: 'MERCEDES BENZ', types: ['otomobil'], country: 'Almanya' },
  { name: 'BMW', sourceName: 'BMW', types: ['otomobil'], country: 'Almanya' },
  { name: 'Renault', sourceName: 'RENAULT', types: ['otomobil'], country: 'Fransa' },
  { name: 'Audi', sourceName: 'AUDI', types: ['otomobil'], country: 'Almanya' },
  { name: 'Volvo', sourceName: 'VOLVO CARS', types: ['otomobil'], country: 'İsveç' },
  { name: 'Ford', sourceName: 'FORD', types: ['otomobil'], country: 'ABD' },
  { name: 'Opel', sourceName: 'OPEL', types: ['otomobil'], country: 'Almanya' },
  { name: 'Peugeot', sourceName: 'PEUGEOT', types: ['otomobil'], country: 'Fransa' },
  { name: 'Seat', sourceName: 'SEAT', types: ['otomobil'], country: 'İspanya' },
  {
    name: 'Skoda',
    sourceName: 'SKODA',
    slug: 'skoda',
    aliasSlugs: ['koda'],
    types: ['otomobil'],
    country: 'Çekya',
  },
  {
    name: 'Citroen',
    sourceName: 'CITROEN',
    slug: 'citroen',
    aliasSlugs: ['citro-n'],
    types: ['otomobil'],
    country: 'Fransa',
  },
  { name: 'Fiat', sourceName: 'FIAT', types: ['otomobil'], country: 'İtalya' },
  { name: 'Hyundai', sourceName: 'HYUNDAI', types: ['otomobil'], country: 'Güney Kore' },
  { name: 'Toyota', sourceName: 'TOYOTA', types: ['otomobil'], country: 'Japonya' },
  { name: 'Kia', sourceName: 'KIA MOTORS', types: ['otomobil'], country: 'Güney Kore' },
  { name: 'Nissan', sourceName: 'NISSAN', types: ['otomobil'], country: 'Japonya' },
  {
    name: 'Dacia',
    sourceName: 'DACIA (RENAULT GROUP)',
    types: ['otomobil'],
    country: 'Romanya',
  },
  { name: 'Land Rover', sourceName: 'LAND ROVER', types: ['otomobil'], country: 'İngiltere' },
  { name: 'Porsche', sourceName: 'PORSCHE', types: ['otomobil'], country: 'Almanya' },
  {
    name: 'DS Automobiles',
    sourceName: 'DS AUTOMOBILES',
    types: ['otomobil'],
    country: 'Fransa',
  },
  { name: 'Mini', sourceName: 'MINI', types: ['otomobil'], country: 'İngiltere' },
  { name: 'Honda', sourceName: 'HONDA', types: ['otomobil'], country: 'Japonya' },
  { name: 'Mazda', sourceName: 'MAZDA', types: ['otomobil'], country: 'Japonya' },
  { name: 'Jeep', sourceName: 'JEEP', types: ['otomobil'], country: 'ABD' },
  { name: 'Iveco', sourceName: 'IVECO', types: ['otomobil'], country: 'İtalya' },
  { name: 'Chevrolet', sourceName: 'CHEVROLET', types: ['otomobil'], country: 'ABD' },
  { name: 'Subaru', sourceName: 'SUBARU', types: ['otomobil'], country: 'Japonya' },
  { name: 'Suzuki', sourceName: 'SUZUKI', types: ['otomobil'], country: 'Japonya' },
  { name: 'Jaguar', sourceName: 'JAGUAR', types: ['otomobil'], country: 'İngiltere' },
  { name: 'Mitsubishi', sourceName: 'MITSUBISHI', types: ['otomobil'], country: 'Japonya' },
  { name: 'Alfa Romeo', sourceName: 'ALFA ROMEO', types: ['otomobil'], country: 'İtalya' },
  { name: 'Smart', sourceName: 'SMART (DAIMLER AG)', types: ['otomobil'], country: 'Almanya' },
  { name: 'Tesla', sourceName: 'TESLA MOTORS', types: ['otomobil'], country: 'ABD' },
  { name: 'Cupra', sourceName: 'CUPRA', types: ['otomobil'], country: 'İspanya' },
  { name: 'SsangYong', sourceName: 'SSANGYONG', types: ['otomobil'], country: 'Güney Kore' },
  { name: 'Isuzu', sourceName: 'ISUZU', types: ['otomobil'], country: 'Japonya' },
  { name: 'Genesis', sourceName: 'GENESIS', types: ['otomobil'], country: 'Güney Kore' },
  { name: 'Haval', sourceName: 'HAVAL', types: ['otomobil'], country: 'Çin' },
  { name: 'Geely', sourceName: 'GEELY', types: ['otomobil'], country: 'Çin' },
  {
    name: 'Volga (GAZ)',
    sourceName: 'VOLGA / GAZ',
    slug: 'volga-gaz',
    types: ['otomobil'],
    country: 'Rusya',
  },

  // ── Yalnızca Ağır Vasıta ───────────────────────────────────────────────────
  { name: 'MAN', sourceName: 'MAN TRUCK', types: ['agir-vasita'], country: 'Almanya' },
  { name: 'Scania', sourceName: 'SCANIA', types: ['agir-vasita'], country: 'İsveç' },
  { name: 'Setra', sourceName: 'SETRA', types: ['agir-vasita'], country: 'Almanya' },
  { name: 'Neoplan', sourceName: 'NEOPLAN', types: ['agir-vasita'], country: 'Almanya' },
  { name: 'DAF', sourceName: 'DAF', types: ['agir-vasita'], country: 'Hollanda' },
  { name: 'Temsa', sourceName: 'TEMSA', types: ['agir-vasita'], country: 'Türkiye' },
  { name: 'Otokar', sourceName: 'OTOKAR', types: ['agir-vasita'], country: 'Türkiye' },
  { name: 'BMC', sourceName: 'BMC', types: ['agir-vasita'], country: 'Türkiye' },

  /*
   * Kamyon/otobüs kolları AYRI MARKA.
   *
   * Kaynak da böyle ayırıyor ("MERCEDES BENZ" ile "MERCEDES", "VOLVO CARS" ile
   * "VOLVO" ayrı sayfalar). Veritabanında model listesi türe göre süzülmediği
   * için aynı markaya koymak, binek Mercedes seçicisinde Actros'u da gösterirdi.
   * `ford-trucks` bu deseni zaten kullanıyordu; kalanlar ona uyduruldu.
   */
  {
    name: 'Mercedes-Benz Kamyon & Otobüs',
    sourceName: 'MERCEDES',
    types: ['agir-vasita'],
    country: 'Almanya',
  },
  { name: 'Volvo Trucks', sourceName: 'VOLVO', types: ['agir-vasita'], country: 'İsveç' },
  { name: 'Renault Trucks', sourceName: 'RENAULT', types: ['agir-vasita'], country: 'Fransa' },
  { name: 'Iveco Trucks', sourceName: 'IVECO', types: ['agir-vasita'], country: 'İtalya' },
  { name: 'Ford Trucks', sourceName: 'FORD', types: ['agir-vasita'], country: 'Türkiye' },
]

/**
 * Marka slug'ı → model adları (kaynaktaki sırayla).
 *
 * Model adları kaynaktaki yazımla korunur; parantez içindeki gövde/şasi kodu
 * (ör. 'A4 (8K, B8)') senkron betiği tarafından `vehicle_model.code` alanına
 * ayrıca çıkarılır. Aynı marka içinde slug çakışması olursa betik sonuna
 * sıra numarası ekler.
 *
 * Bu haritada olmayan markalar (ekran görüntüleri henüz gelmedi) modelsiz
 * kalır — marka kaydı oluşur, model oluşmaz.
 */
export const REAL_MODELS: Record<string, string[]> = {
  'alfa-romeo': ['156', '159', 'Giulietta (940)', 'MiTo', 'Stelvio (949)', 'Tonale (965)'],

  audi: [
    'A5 (8T, 8F)',
    'A4 (8K, B8)',
    'A4 (8E/8H, B6+B7)',
    'A6 (4F/C6)',
    'Q5 (8R)',
    'A3 (8P)',
    'A6 (4G2/4G5/4GC/4GD)',
    'A4 (8W)',
    'Q5 II (FY)',
    'A3 (8YA, 8YS)',
    'Q3 (8U)',
    'A6 (4A_/C8)',
    'A1 (8X)',
    'Q7 (4L)',
    'A3 (8VA/8VS/8V7)',
    'A7 (4GA/GF)',
    'A7 (4K)',
    'Q3 (F3)',
    'A5 + A5 Cabriolet + Sportback (F5)',
    'TT/TTS/TTRS II (8J)',
    'A5 (F5)',
    'A8 (4H)',
    'TT/TTS/TTRS III (FV)',
    'Q2 (GA)',
    'A6 (4B/C5)',
    'Q7 (4M)',
    'Q8 (4M)',
    'TT I (8N)',
    'A3 (8L)',
    'A8 (4N)',
    'A8 (4E)',
    'A6 (4A)',
    'A4 (8D, B5)',
    'A1 (GB)',
    'Q8 E-Tron (GET, GEG)',
    'A8 (4D)',
    'E-Tron (GE)',
    'E-Tron GT',
  ],

  bmw: [
    '3 (E90/E91/E92/E93)',
    '5 (G30, G31, F90)',
    '3 (G20, G21, G80, G81)',
    '3 (F30/F31/F80)',
    '5 (F10/F11/F18)',
    '1 (E81/E82/E87/E88)',
    '5 (E60/E61)',
    'X1 (E84)',
    '3 (E46)',
    'X3 (E83)',
    '1 (F20/F21)',
    'X1 (F48)',
    '4 (F32/F33/F36/F82)',
    'X3 (G01, F97)',
    'X3 (G01)',
    '3 (G20)',
    'X4 (G02)',
    'X5 (G05)',
    '3 GT (F34)',
    '4 (G22, G23, G26, G82, G83)',
    '6 Gran Turismo (G32GT)',
    '2 (F22, F23, F87)',
    'X3 (F25)',
    'X4 (G02, F98)',
    '2 Active/Gran Tourer/Gran Coupe (F44, F45, F46)',
    'X5 (E70)',
    'X6 (G06, F96)',
    '1 (F40)',
    '5 (E39)',
    '7 (E65/E66)',
    '7 (G11/G12)',
    'X5 (G05, F95)',
    'X2 (F39)',
    '2 (G42, G87)',
    'X1 (U11)',
    '5 GT (F07GT)',
    '2 Active/Gran Tourer (F45, F46)',
    'X4 (F26)',
    'X7 (G07)',
    'Z4 (E85/E86)',
    'X5 (F15, F85)',
    '2 Active Tourer (U06)',
    'X6 (E71, E72)',
    '7 (F01/F02/F03/F04)',
    'Z4 (E89)',
    'X5 (E53)',
    '6 (E63/E64)',
    '3 (E36)',
    '7 (E38)',
    '8 (G14, G15, G16, F91, F92, F93)',
    'X6 (F16, F86)',
    'i4 (G26)',
    'iX3 (G08)',
    'Z4 (G29)',
    'i3 (I01)',
    '7 (G70)',
  ],

  chevrolet: ['Cruze', 'Aveo', 'Aveo II', 'Captiva', 'Lacetti', 'Kalos', 'Captiva II'],

  citroen: [
    'C4',
    'C3 II (A51)',
    'DS3',
    'Jumper III',
    'DS4',
    'C4 II (B7)',
    'Berlingo II (B9)',
    'C4 Picasso II (B78)',
    'C4 Picasso',
    'C5',
    'C5 II',
    'Xsara Picasso',
    'C3 (FC)',
    'Xsara',
    'C3 Picasso',
    'C2',
    'C3 III (B618)',
    'C4 SpaceTourer',
    'Berlingo III (K9)',
    'C4 Cactus',
    'Berlingo I (M49, M59)',
    'Jumper II (Relay II)',
    'DS5',
    'C4 III (C41) / C4 X (C43)',
    'Jumper III (Relay III)',
    'C5 Aircross',
    'C-Elysée',
    'Nemo',
    'C4 Sedan',
    'Jumpy III (Dispatch III) K0',
    'Spacetourer',
    'C3 Aircross (A88)',
  ],

  cupra: ['Formentor'],

  dacia: [
    'Duster I',
    'Sandero',
    'Duster II',
    'Logan',
    'Sandero II',
    'Logan II',
    'Lodgy',
    'Dokker',
    'Sandero III',
    'Jogger',
    'Logan III',
    'Logan II / MCV II',
    'Spring',
  ],

  'ds-automobiles': [
    'DS3',
    'DS4',
    'DS5',
    'DS4 II',
    'DS9',
    'DS7 / DS7 CROSSBACK',
    'DS3 Crossback',
    'DS7 CROSSBACK',
  ],

  fiat: [
    'Doblo',
    'Ducato 2007 (250/251/252/254/290)',
    'Punto III',
    'Punto II (188/188AX)',
    '500X',
    'Idea (135/235)',
    'Panda III',
    '500',
    'Ducato 2002 (244)',
    'Scudo II (272)',
    '500L',
    'Panda II (169A)',
    'Fiorino (225)',
    'Scudo III (506, 507)',
    'Scudo I (220)',
    'Doblo (510, 511)',
    '500 / Nuova 500 (150)',
    'Aegea (356)',
    'Tipo / Egea (356)',
    'Ducato 94 (230/231/232/234)',
    'Linea (110)',
    'Fiorino (127/146/147)',
  ],

  ford: [
    'C-Max II',
    'Mondeo IV',
    'Transit 2007',
    'Transit 2014',
    'Kuga II',
    'Fiesta VII',
    'Focus II',
    'Transit Custom 2012',
    'Kuga III',
    'Tourneo Custom 2012',
    'Transit 2000',
    'Mondeo III (B4Y/5Y/BWY)',
    'Focus III',
    'C-Max',
    'S-Max',
    'Transit Connect',
    'Tourneo Connect II',
    'Focus C-Max',
    'Mondeo V',
    'Fiesta V',
    'Ranger 2012',
    'B-MAX',
    'Focus IV',
    'Puma II',
    'Fiesta VIIII',
    'Fusion / Fusion Plus',
    'Transit Connect (TC7)',
    'Tourneo Connect',
    'Fiesta VII / Fiesta Mk VIII',
    'Fiesta IV',
    'Tourneo Connect III / Grand Tourneo Connect',
    'Transit Connect III',
    'Kuga I',
    'S-Max II',
    'Transit / Tourneo Courier (C4A)',
    'Focus I',
    'Ranger (TRA, TRB)',
    'Ecosport',
    'Ranger',
    'Ranger 2006',
    'Fiesta Courier II',
    'Mondeo II (BAP/BFP/BNP)',
    'Transit 95',
    'Galaxy III',
  ],

  geely: ['Tugella'],

  genesis: ['GV60 (JW)', 'G70', 'GV70', 'G80 II (RG)'],

  haval: ['Jolion', 'H7 / H7x'],

  honda: [
    'Civic VIII',
    'Civic VII',
    'Accord IX',
    'Civic IX',
    'CR-V III',
    'CR-V IV',
    'Accord VIII',
    'Jazz II',
    'FR-V',
    'Jazz III',
    'HR-V II',
    'Civic X',
    'City',
    'Jazz IV',
    'HR-V',
    'Civic XI (FL)',
    'CR-Z',
    'CR-V II',
    'CR-V I',
    'CR-V V (RW)',
    'Jazz V / Fit V (GR)',
    'Accord X',
  ],

  hyundai: [
    'i30',
    'Tucson II (TL)',
    'ix35 / Tucson',
    'Accent II',
    'H-1 Starex',
    'i20',
    'Getz',
    'Santa Fé I',
    'Santa Fe',
    'Santa Fé',
    'i20 III (BC3)',
    'Tucson',
    'Santa Fé II',
    'Tucson III (NX4E)',
    'ix20',
    'Sonata V (NF)',
    'i20 II',
    'Elantra',
    'Bayon',
    'i10',
    'Kona',
    'i30 + i30 cw (PD, PDE)',
    'Accent IV (RB)',
    'Accent III',
    'Elantra II',
    'Ioniq 5 (NE)',
    'Sonata IV (EU4 / EF-B)',
    'i10 II',
    'Atos',
    'Sonata VIII (DN8)',
    'Venue (QX, QXI)',
    'i10 III',
    'Ioniq (AE)',
    'Elantra III (MD)',
    'Santa Fé IV',
    'Elantra VII',
    'Staria (US4)',
    'H350 II',
    'H100',
    'Ioniq 6',
  ],

  isuzu: ['D-MAX'],

  iveco: ['Daily', 'Daily VI (14-)', 'Daily III', 'Daily IV'],

  jaguar: [
    'E-Pace (X540)',
    'XF (X250)',
    'X-Type (CF1)',
    'F-Pace (X761)',
    'XE (X760)',
    'XF',
    'S-Type (CCX)',
    'XF, XF Sportbrake (X260)',
    'F-Type',
    'I-PACE (X590)',
  ],

  jeep: [
    'Compass II (MP)',
    'Renegade',
    'Grand Cherokee',
    'Renegade (BU)',
    'Compass',
    'Cherokee',
    'Grand Cherokee III (WH)',
    'Patriot',
    'Avenger (J2)',
    'Wrangler III (JK)',
    'Wrangler II (TJ)',
    'Wrangler IV (JL)',
  ],

  kia: [
    'Sportage',
    'Rio',
    'Ceed',
    "Cee'd III / Pro Cee'd III / XCee'd (CD)",
    'Ceed II / Pro_Ceed II',
    'Cerato I (LD)',
    'Optima',
    'Soul III (SK3)',
    'Sorento',
    'Sportage V (NQ_)',
    'Sorento I (JC)',
    'Picanto',
    'Seltos (SP2, SP2I)',
    'Picanto I (BA)',
    'Soul II (PS)',
    'Stonic (YB)',
    'EV6 (CV)',
    'Sorento IV (MQ4)',
    'Optima V / K5',
    'Cerato III',
    'Sportage IV (QL, QLE)',
    'Cerato II',
    'Carnival III / Sedona III (VQ)',
    'Cerato IV (BD, BDM)',
    'Carnival IV / Sedona (KA4)',
    'Niro II',
    'Picanto III (JA)',
    'Sportage I (JA)',
  ],

  'land-rover': [
    'Discovery Sport (L550)',
    'Range Rover Sport',
    'Discovery 4',
    'Range Rover Sport II (LW, L494)',
    'Range Rover Evoque',
    'Defender (L663)',
    'Range Rover Velar (L560)',
    'Freelander II',
    'Discovery Sport',
    'Range Rover',
    'Range Rover Evoque (L551)',
    'Range Rover IV (L405)',
    'Discovery 5 / LR5',
    'Freelander I',
    'Defender',
    'Discovery 5',
    'Range Rover IV',
    'Discovery 3',
    'Discovery 2',
    'Range Rover Sport III (L461)',
    'Range Rover V (L460)',
  ],

  mazda: ['6', '3', 'CX-5', '323 VI', 'MX-5', '626', 'CX-3'],

  'mercedes-benz': [
    'E W S211',
    'Sprinter 906',
    'C W203 C203 S203',
    'C W204 C204 S204',
    'E W S212',
    'C W205 A205 C205 S205',
    'Vito 639',
    'E C207',
    'Sprinter III (907, 910)',
    'M W164',
    'GLC / GLC Coupe (X253/C253)',
    'Sprinter 901 902 903 904',
    'CLK C209',
    'GLK X204',
    'Vito III (447)',
    'Viano 639',
    'CLC C203',
    'CLA (C118/W118/X118)',
    'E-Klasse, E-Klasse Cabrio (W/S213, A/C238)',
    'R W251',
    'A W176',
    'A W169',
    'A W177',
    'E W S210',
    'E S213 A238',
    'C-Klasse (W206/S206)',
    'GLA (H247)',
    'S W221',
    'GLE / GLS / GLE Coupe (W167)',
    'GL X164',
    'CLA C117',
    'GLA X156',
    'Citan W415',
    'V II 447',
    'GLB (X247)',
    'B W245',
    'S W220',
    'CLS C257',
    'Citan (W420)',
    'CLS C219',
    'CLS C218',
    'Sprinter 907 910',
    'B W247',
    'Vito 447',
    'A W168',
    'B W246 W242',
    'SLK R171',
    'M W163',
    'SLK R172',
    'T-Klasse (W420)',
    'SLK R170',
    'SL R230',
    'S-Klasse (W/C/V/223)',
    'V 638 2',
    'G-Klasse (W463) 2018-',
    'SLC R172',
    'GLC GLC Coupé X253 C253',
    'GLC (X254/C254)',
    'Vito 638',
    'CLK C208',
    'C W202 S202',
    'M W166',
    'GLE W166',
    'CLA W118',
    'X W470',
    'S W222 A C217',
    'GL GLS',
    'SL (R232)',
    'Vaneo W414',
    'EQB (X243)',
    'EQA (W/H243)',
    'EQV (W447)',
    'Maybach II (X222)',
    'GLE W167',
    'EQC (W293)',
    'GLE Coupé C292',
    'G-Klasse (W464)',
  ],

  mini: [
    'Mini III',
    'Mini Cooper II,Cabr,Coupé,Club/Country/Pacem./Road',
    'Mini One II, Cabrio, Clubman, Countryman',
    'Mini III (F54, F55, F56, F57, F60)',
    'Mini One I',
    'Mini Cooper I',
  ],

  mitsubishi: [
    'L200',
    'Carisma',
    'Pajero III',
    'Colt VI/Colt CZ3/CZC/CZT (Z30)',
    'Colt V (CJ0)',
    'L 200',
    'Outlander III',
    'Space Star II',
  ],

  nissan: [
    'Almera II (N16)',
    'Qashqai II',
    'Qashqai',
    'NV300 / Primastar (X82)',
    'Note (E11)',
    'Navara (D40)',
    'Primera III (P12)',
    'NV400 / Interstar (X62, X62B)',
    'Pathfinder',
    'Micra III (K12)',
    'Juke',
    'Micra V (K14F)',
    'Micra IV (K13)',
    'NV250',
    'X-Trail III (T32)',
    'Terrano III (D10)',
    'Micra II (K11)',
    'Juke (F16E)',
    'Pick Up / Navara (720, D21, D22)',
    'Townstar (XFK)',
    'Note (E12)',
    'Navara NP300 (D23)',
    'Qashqai III (J12)',
    'Almera (G15)',
    'Primera II (P11)',
    'NP300 Pick Up',
    'X-Trail IV (T33)',
    'Almera Classic',
  ],

  opel: [
    'Astra G / Astra G Cabrio/Coupé',
    'Insignia',
    'Corsa D',
    'Astra H / Astra H GTC',
    'Astra J / Astra J GTC',
    'Corsa-C',
    'Vectra-C',
    'Meriva B',
    'Combo D (X12)',
    'Meriva A',
    'Mokka, Mokka X',
    'Vivaro A',
    'Astra K',
    'Vivaro B',
    'Zafira B',
    'Combo B',
    'Vivaro C (K0)',
    'Insignia B (Z18)',
    'Corsa E',
    'Cascada',
    'Vectra-B',
    'Omega-B',
    'Movano C',
    'Zafira C',
    'Zafira A',
    'Mokka B',
    'Combo E (X19)',
    'Astra L',
    'Antara',
    'Corsa-F',
    'Movano A',
    'Agila',
    'Grandland X',
    'Combo A',
    'Movano B',
    'Crossland X',
    'Adam',
    'Frontera',
  ],

  peugeot: [
    'Boxer III',
    '307',
    '308',
    '208',
    '308 II',
    'Partner II',
    '3008',
    '5008',
    '2008',
    '3008 II',
    '207',
    '508',
    '206',
    '407 + 407 Coupé',
    '208 II',
    '508 II (R8)',
    '2008 II',
    'Expert II',
    'Partner',
    '406 + 406 Coupé',
    'Partner III (K9)',
    '5008 II (P87)',
    'Expert III (K0)',
    'Boxer II',
    '408',
    '308 III',
    '206+',
    '306',
    'Boxer I',
    'Bipper',
    '408 II',
    '301',
    'Rifter (K9)',
  ],

  porsche: [
    'Cayenne II (92A)',
    'Boxster',
    'Cayenne I (9PA)',
    'Macan',
    'Cayman / Cayman R, S, T, GT4',
    'Panamera I (970)',
    '911 (996)',
    '911 (991)',
    '911 (997)',
    '911 (992)',
    'Boxster / Boxster S, T',
    'Cayenne III (9YA, 9YB)',
    'Panamera II (971)',
    'Cayenne III (9YA)',
    'Taycan',
    '918 Spyder',
  ],

  renault: [
    'Kangoo',
    'Duster I',
    'Laguna II',
    'Clio III / Clio Collection',
    'Trafic III',
    'Scénic III',
    'Master IV',
    'Modus / Grand Modus',
    'Mégane II',
    'Mégane I',
    'Laguna III',
    'Sandero',
    'Scénic II',
    'Kangoo II',
    'Trafic II',
    'Scénic I',
    'Logan',
    'Talisman',
    'Mégane III',
    'Fluence',
    'Captur II (HF)',
    'Clio V',
    'Clio II / Clio Symbol',
    'Scénic IV',
    'Twingo II',
    'Clio IV',
    'Master III / Master Maxi',
    'Espace IV / Grand Espace IV',
    'Kadjar',
    'Captur (J5, H5)',
    'Duster II',
    'Sandero II',
    'Koleos II (HZG)',
    'Symbol',
    'Kangoo III',
    'Mégane IV',
    'Logan II',
    'Espace V',
    'Lodgy',
    'Dokker',
    'Express',
    'Master II',
    'Koleos',
    'Espace III / Grand Espace III',
    'Kangoo II / Grand Kangoo',
    'Latitude',
    'Austral',
    'Megane IV',
    'Laguna I',
    'Twingo I',
    'Kaptur (Russia)',
    'Twingo III',
    'ZOE',
    'Megane E-Tech',
    'Trafic I',
  ],

  seat: [
    'Ibiza V',
    'Ibiza IV',
    'Leon III',
    'Leon II',
    'Leon IV (KL1, KL8)',
    'Cordoba III',
    'Leon I',
    'Toledo IV',
    'Ibiza III',
    'Alhambra II (71)',
    'Ateca',
    'Cordoba II',
    'Altea',
    'Toledo II',
    'Ibiza VI',
    'Toledo III',
    'Alhambra I (7V)',
    'Exeo',
    'Arona (KJ)',
  ],

  skoda: [
    'Octavia III',
    'Octavia IV',
    'Fabia II',
    'Fabia I',
    'Octavia II',
    'Roomster',
    'Rapid (NH3, NH1)',
    'Yeti (5J, 5L)',
    'Octavia I',
    'Kodiaq',
    'Karoq',
    'Fabia III',
    'Superb III (3V)',
    'Superb II (3T)',
    'Scala',
    'Kamiq',
    'Fabia IV (PJ3)',
    'Superb I (3U)',
    'Rapid (NA2)',
  ],

  ssangyong: ['Kyron', 'Actyon', 'Korando'],

  subaru: [
    'Impreza II (GD/GG)',
    'Legacy III / Liberty',
    'Legacy IV',
    'Forester (SG)',
    'Impreza III (G3, GH, GR)',
    'Forester (SH)',
    'Outback III',
    'Outback II',
    'Impreza IV (GJ, GP)',
    'Forester (SJ)',
    'Impreza V (GK, GT)',
    'Outback I',
    'Outback IV',
    'Forester (SF)',
    'Outback V',
    'Legacy II',
    'Levorg',
    'XV II (GT3/GT7/GTE)',
  ],

  suzuki: [
    'SX4',
    'Grand Vitara',
    'Swift III (MZ/EZ/SG)',
    'Swift IV (AZG/AZH)',
    'Vitara II',
    'Jimny I',
    'Swift V (AZ)',
    'Alto',
    'Vitara',
    'SX4 S-Cross',
    'S-Cross',
    'Across',
    'Carry',
    'Jimny II',
    'Swift II (EA/MA)',
  ],

  tesla: ['Model Y', 'Model 3', 'Model S', 'Model X'],

  smart: [
    'City-Coupé/Cabrio/Fortwo (450)',
    'Forfour (454)',
    'Fortwo Coupé',
    'Fortwo Forfour (453)',
    'Roadster',
  ],

  toyota: [
    'Corolla IX (E12/E13)',
    'HiLux',
    'Corolla (E210)',
    'Corolla X (E14/E15)',
    'Avensis III (T27)',
    'Proace II / Proace City / Proace Verso',
    'Yaris I / Yaris Verso (P1)',
    'Land Cruiser',
    'Prius',
    'Yaris III (XP13)',
    'RAV 4 IV',
    'Auris I (E150)',
    'Verso',
    'Avensis II (T25)',
    'Corolla XI (E18)',
    'Auris II (E180)',
    'Yaris II (XP9)',
    'Corolla IX Verso',
    'Avensis I (T22)',
    'Yaris IV / Yaris Cross',
    'Corolla VIII (E11)',
    'RAV 4 II',
    'Avensis Verso',
    'Camry VII',
    'Verso-S',
    'RAV 4 III',
    'Camry VIII',
    'HIACE VI',
    'C-HR',
    'RAV 4 V',
    'Corolla',
    'Camry VI',
    'Hilux VIII / Hilux Revo',
    'Corolla Cross',
    'Yaris / Vios (ZSP9, NCP9)',
    'GT86',
    'Camry IV',
    'Camry V',
    'Highlander II',
    'Aygo X',
    'Highlander I',
    'GR 86 (ZN8)',
  ],

  'volga-gaz': ['Gazelle Next'],

  volkswagen: [
    'Polo V',
    'Touran',
    'Golf VII',
    'Transporter (T5)',
    'Polo IV (9N)',
    'Golf VI / Golf Plus',
    'Golf V / Golf Plus',
    'Golf VIII',
    'Caravelle T5',
    'Passat (3C2/3C5) / Passat CC (357)',
    'Jetta III (1K2)',
    'Scirocco III',
    'Tiguan I',
    'Caddy III',
    'Polo III',
    'Caddy IV',
    'Tiguan II',
    'Passat (3B3/3B6)',
    'Sharan II',
    'Passat (3G2, 3G5)',
    'Passat (362, 365) / Passat CC (357)',
    'Arteon (3H)',
    'CC (358)',
    'Caravelle T6',
    'Crafter 30, 35, 50',
    'Transporter (T6)',
    'Jetta IV (162)',
    'Eos (1F7, 1F8)',
    'Touareg I',
    'Amarok (2H)',
    'Caddy V (SB)',
    'Bora (1J2,1J6)',
    'New Beetle',
    'Golf IV (1J1, 1J5)',
    'Polo VI (AW)',
    'Touareg II',
    'Tiguan II (AD1, AX1)',
    'T-Roc (A1)',
    'Beetle (5C)',
    'LT 46',
    'LT 35 II',
    'LT 28 II',
    'Fox (5Z1)',
    'Touran (5T)',
    'Transporter/Bus (T7)',
    'Touareg III',
    'Sharan I',
    'Crafter II 30, 35',
    'T-Roc / T-Roc Cabrio (A1)',
    'Caravelle (Multivan/Californ.) T6',
    'Transporter/Bus (T6)',
    'Passat B8 (3G2, 3G5)',
    'Tiguan Allspace (BW2, BJ2)',
    'Taigo (Nivus)',
    'Amarok II (T1A, T1B)',
    'T-Cross (C11)',
    'Touareg III (CR)',
    'Transporter (T4)',
    'Passat (3B2/3B5)',
    'Golf VII (5G1/BA5)',
    'Caddy II (9K9, 9U7)',
    'Sharan III',
    'Crafter II 30, 35 (SY, SZ, UZ)',
    'Up / Load Up',
    'Caddy IV (2K, SA, SE)',
  ],

  volvo: [
    'V70 II',
    'S60 II / V60',
    'XC60',
    'S80 II',
    'V70',
    'S60',
    'XC60 II',
    'XC70 II',
    'V50',
    'S60 III / V60 II / V60 II Cross Country',
    'V40 II',
    'S40 II',
    'S80',
    'C30',
    'XC40 (536)',
    'XC90',
    'XC90 II',
    'S90 II / V90 II / V90 II Cross Country',
    'C70 II',
    'S40 I',
    'V40',
    'XC70',
    'S90 II / V90 II',
    'C70 I',
    'V70 III',
    'S60 III / V60 II',
    'XC40',
    'Polestar II',
    'C40 (539)',
    'S70',
  ],

  /*
   * ── AĞIR VASITA ───────────────────────────────────────────────────────────
   * Kaynağın kamyon/otobüs sayfalarından okundu (13 marka · 99 model).
   * Kamyon kolları ayrı marka: Mercedes-Benz Kamyon & Otobüs · Volvo Trucks ·
   * Renault Trucks · Iveco Trucks · Ford Trucks. Iveco'nun Daily'leri binek
   * tarafında (`iveco`) kalır; burada yalnız EuroCargo/Stralis/EuroMover var.
   */
  bmc: ['Professional', 'Probus', 'Procity', 'Fatih'],
  daf: ['CF75', 'New XF (XF106)', 'CF85', 'XF105'],
  'ford-trucks': ['Cargo F-Max', 'Cargo'],
  'iveco-trucks': [
    'EuroCargo III',
    'Stralis',
    'EuroMover (00-)',
    'EucoCargo IV (15-)',
    'EuroCargo II',
    'Stralis II',
  ],
  man: ['TGL (05-)', 'TGS (07-)', 'TGX (07-)', 'TGA (2000-2007)'],
  'mercedes-benz-kamyon-otobus': [
    'Atego II (970, 972, 974) 04-',
    'Actros II (963 / MP4) 11-',
    'Arocs (964)',
    'Atego III (967) 13-',
    'Econic (956 + 957) 98-',
    'Axor II (940, 942, 943, 944, 950, 954) 04-',
    'Zetros (949.016 - 949.066)',
    'Vario (667, 668, 669, 670) 96-',
    'Antos (963)',
    'Actros I',
  ],
  neoplan: [
    'Tourliner',
    'Centroliner / Centroliner Evolution',
    'Starliner II / Starliner C / L',
    'Trendliner',
    'Cityliner II',
    'Jetliner II',
    'Skyliner',
    'Tourliner C (P10)',
  ],
  otokar: ['NAVIGO', 'KENT', 'VECTIO', 'TERRITO'],
  'renault-trucks': [
    'Premium Distribution/Route',
    'Midlum II',
    'Kerax',
    'C (C250 - C520, 2013-)',
    'T (T380 - T520)',
    'Access',
    'Premium Lander',
    'Mascott',
    'K (K380 - K520)',
    'Magnum',
    'D / D Access (D150 - D430, 2013-)',
  ],
  scania: [
    'R (R230 - R730)',
    'P New Generation (P220 - P500)',
    'T (T340 - T580)',
    'G New Generation (G280 - G500)',
    'R New Generation (R410 - R730), S (S410 - S730)',
    'L (L220 - L360)',
    'P (P230 - P490)',
    'G (G230 - G490)',
  ],
  setra: [
    'Setra S 400',
    'Integro II (633)',
    'Setra S 500',
    'Citaro (O 530 / 628)',
    'Tourismo II (632)',
    'CapaCity (O 530 GL / 628)',
    'O 810 - 818 (Vario)',
    'Conecto II (628)',
    'Citaro LE (O 530 / 628)',
    'Citaro K (O 530 / 628)',
    'Tourino (O 510 / 444)',
    'O 400',
    'Citaro 2012 (628)',
    'Intouro II (633)',
    'Intercity (634)',
    'Medio (O 815 / 670)',
    'Setra S 400 11.2007-',
    'Travego (O 580 / 629 + 632)',
  ],
  temsa: [
    'Diamond',
    'Safari HD/IC/RD/STD',
    'Metropol',
    'Opalin',
    'Maraton',
    'Safir, Safir Plus',
    'MD9',
    'Avenue LF',
    'Tourmalin, Tourmalin IC',
  ],
  'volvo-trucks': [
    'FM / FMX / FMX Classic (05-)',
    'FE II (06-)',
    'FH 16, FH 16 Classic (93-)',
    'FM II / FMX II (New FM / FMX 2013-)',
    'FE III (13-)',
    'VT (06-)',
    'CF75',
    'FH II (New FH 2013)',
    'VN (00-)',
    'FH, FH Classic (05-)',
    'FL II (06-)',
  ],
}
